import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn, execFileSync } from 'node:child_process';
import { mkdtemp, rm, readdir, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import net from 'node:net';

const freePort=()=>new Promise(resolvePort=>{const server=net.createServer();server.listen(0,'127.0.0.1',()=>{const port=server.address().port;server.close(()=>resolvePort(port));});});
const pause=ms=>new Promise(r=>setTimeout(r,ms));
test('multi-user registration, isolation, optimistic conflict and admin boundary',async()=>{
  const data=await mkdtemp(join(tmpdir(),'yanxi-test-')),port=await freePort(),base=`http://127.0.0.1:${port}`;
  const child=spawn(process.execPath,[resolve('server.mjs')],{cwd:resolve('.'),env:{...process.env,PORT:String(port),HOST:'127.0.0.1',DATA_DIR:data,APP_ORIGIN:base,MAIL_MODE:'file',DATABASE_URL:'',PGHOST:'',NODE_ENV:'test'},stdio:['ignore','pipe','pipe']});
  let output='';child.stdout.on('data',chunk=>output+=chunk);child.stderr.on('data',chunk=>output+=chunk);
  const api=async(path,method='GET',body,cookie='')=>{const res=await fetch(base+path,{method,headers:{...(body?{'content-type':'application/json'}:{}),...(cookie?{cookie}:{})},body:body?JSON.stringify(body):undefined});return {status:res.status,data:await res.json(),cookie:res.headers.get('set-cookie')?.split(';')[0]};};
  try{
    for(let i=0;i<60&&!output.includes('初始化口令');i++)await pause(100);
    const token=output.match(/初始化口令（仅服务器终端显示）：([^\r\n]+)/)?.[1];assert.ok(token,output);
    assert.equal((await api('/api/config')).data.setupRequired,true);
    assert.equal((await api('/api/register','POST',{username:'admin',email:'admin@example.test',password:'strong-password-1',setupToken:'wrong'})).status,403);
    const admin=await api('/api/register','POST',{username:'admin',email:'admin@example.test',password:'strong-password-1',setupToken:token,displayName:'Owner'});
    assert.equal(admin.status,200);assert.equal(admin.data.user.role,'admin');
    const pending=await api('/api/register','POST',{username:'alice',email:'alice@example.test',password:'strong-password-2',displayName:'Alice'});
    assert.equal(pending.status,202);assert.equal(pending.data.pendingVerification,true);
    assert.equal((await api('/api/login','POST',{username:'alice',password:'strong-password-2'})).status,401);
    const mailDir=join(data,'dev-mailbox'),files=await readdir(mailDir),mail=JSON.parse(await readFile(join(mailDir,files[0]),'utf8'));
    const verifyToken=new URL(mail.link).hash.slice('#verify='.length);
    assert.equal((await api('/api/verify-email','POST',{token:verifyToken})).status,200);
    assert.equal((await api('/api/verify-email','POST',{token:verifyToken})).status,400);
    const user=await api('/api/login','POST',{username:'alice',password:'strong-password-2'});
    assert.equal(user.status,200);assert.equal(user.data.user.role,'user');
    const vault=structuredClone(admin.data.vault);vault.experiments.push({id:'private-1',sampleId:'SECRET',material:'UTe₂',updatedAt:new Date().toISOString()});
    assert.equal((await api('/api/vault','PUT',{revision:0,vault},admin.cookie)).status,200);
    assert.equal((await api('/api/me','GET',null,user.cookie)).data.vault.experiments.length,0);
    assert.equal((await api('/api/admin/users','GET',null,user.cookie)).status,403);
    assert.equal((await api('/api/vault','PUT',{revision:0,vault},admin.cookie)).status,409);
    const users=await api('/api/admin/users','GET',null,admin.cookie);
    assert.equal(users.data.users.length,2);assert.equal('vault' in users.data.users[1],false);
    assert.equal((await api('/api/admin/registration','POST',{open:false},admin.cookie)).data.registrationOpen,false);
    assert.equal((await api('/api/register','POST',{username:'third',email:'third@example.test',password:'strong-password-3'})).status,403);
    assert.equal((await api('/api/request-reset','POST',{email:'alice@example.test'})).status,200);
    const resetFiles=(await readdir(mailDir)).filter(f=>!files.includes(f));
    assert.equal(resetFiles.length,1);
    const resetMail=JSON.parse(await readFile(join(mailDir,resetFiles[0]),'utf8'));
    const resetToken=new URL(resetMail.link).hash.slice('#reset='.length);
    assert.equal((await api('/api/reset-password','POST',{token:resetToken,newPassword:'new-strong-password'})).status,200);
    assert.equal((await api('/api/reset-password','POST',{token:resetToken,newPassword:'another-password'})).status,400);
    assert.equal((await api('/api/me','GET',null,user.cookie)).status,401);
    assert.equal((await api('/api/login','POST',{username:'alice',password:'strong-password-2'})).status,401);
    const recovered=await api('/api/login','POST',{username:'alice',password:'new-strong-password'});
    assert.equal(recovered.status,200);
    assert.equal((await api('/api/email','POST',{email:'alice.new@example.test',password:'wrong'},recovered.cookie)).status,400);
    assert.equal((await api('/api/email','POST',{email:'alice.new@example.test',password:'new-strong-password'},recovered.cookie)).status,200);
    assert.equal((await api('/api/login','POST',{username:'alice',password:'new-strong-password'})).status,401);
    const changedMail=JSON.parse(await readFile(join(mailDir,(await readdir(mailDir)).find(f=>!files.includes(f)&&f!==resetFiles[0])),'utf8'));
    assert.equal(changedMail.to,'alice.new@example.test');
    assert.equal((await api('/api/verify-email','POST',{token:new URL(changedMail.link).hash.slice('#verify='.length)})).status,200);
    assert.equal((await api('/api/login','POST',{username:'alice.new@example.test',password:'new-strong-password'})).status,200);
    assert.equal((await api('/api/admin/status','POST',{userId:user.data.user.id,disabled:true},admin.cookie)).status,200);
    assert.equal((await api('/api/me','GET',null,recovered.cookie)).status,401);
    const shell=await fetch(base+'/');assert.equal(shell.status,200);assert.match(await shell.text(),/研析 · 研究生工作平台/);
    const staticFile=await fetch(base+'/app.mjs');assert.equal(staticFile.status,200);
    assert.equal((await fetch(base+'/data/workbench.sqlite')).status,404);
  }finally{child.kill();await new Promise(resolveExit=>child.once('exit',resolveExit));await rm(data,{recursive:true,force:true});}
});

test('LAN mode works without mail and permits administrator-mediated password recovery',async()=>{
  const data=await mkdtemp(join(tmpdir(),'yanxi-lan-test-')),port=await freePort(),base=`http://127.0.0.1:${port}`;
  const child=spawn(process.execPath,[resolve('server.mjs')],{cwd:resolve('.'),env:{...process.env,PORT:String(port),HOST:'127.0.0.1',DATA_DIR:data,APP_ORIGIN:base,DEPLOY_MODE:'lan',DATABASE_URL:'',PGHOST:'',NODE_ENV:'test'},stdio:['ignore','pipe','pipe']});
  let output='';child.stdout.on('data',chunk=>output+=chunk);child.stderr.on('data',chunk=>output+=chunk);
  const api=async(path,method='GET',payload,cookie='')=>{const res=await fetch(base+path,{method,headers:{...(payload?{'content-type':'application/json'}:{}),...(cookie?{cookie}:{})},body:payload?JSON.stringify(payload):undefined});return {status:res.status,data:await res.json(),cookie:res.headers.get('set-cookie')?.split(';')[0]};};
  try{
    for(let i=0;i<60&&!output.includes('初始化口令');i++)await pause(100);
    const setupToken=output.match(/初始化口令（仅服务器终端显示）：([^\r\n]+)/)?.[1];assert.ok(setupToken,output);
    assert.equal((await api('/api/config')).data.recoveryMode,'admin');
    const admin=await api('/api/register','POST',{username:'owner',displayName:'Owner',password:'strong-password-1',setupToken});
    assert.equal(admin.status,200);assert.equal(admin.data.user.email,'');
    const member=await api('/api/register','POST',{username:'member',displayName:'Member',password:'strong-password-2'});
    assert.equal(member.status,200);assert.equal(member.data.user.role,'user');
    assert.equal((await api('/api/login','POST',{username:'member',password:'strong-password-2'})).status,200);
    assert.equal((await api('/api/admin/reset-link','POST',{userId:member.data.user.id},member.cookie)).status,403);
    const issued=await api('/api/admin/reset-link','POST',{userId:member.data.user.id},admin.cookie);
    assert.equal(issued.status,200);assert.equal(issued.data.expiresInMinutes,15);
    const token=new URL(issued.data.link).hash.slice('#reset='.length);
    assert.equal((await api('/api/reset-password','POST',{token,newPassword:'new-strong-password'})).status,200);
    assert.equal((await api('/api/reset-password','POST',{token,newPassword:'another-password'})).status,400);
    assert.equal((await api('/api/me','GET',null,member.cookie)).status,401);
    const recovered=await api('/api/login','POST',{username:'member',password:'new-strong-password'});
    assert.equal(recovered.status,200);
    assert.match((await api('/api/request-reset','POST',{email:'none@example.test'})).data.message,/管理员/);
    assert.equal((await api('/api/resend-verification','POST',{email:'none@example.test'})).status,404);
    assert.equal((await api('/api/email','POST',{email:'none@example.test',password:'new-strong-password'},recovered.cookie)).status,404);
    assert.equal((await fetch(base+'/.env.lan')).status,404);
    const operatorOutput=execFileSync(process.execPath,['scripts/issue-admin-reset.mjs'],{cwd:resolve('.'),env:{...process.env,DATA_DIR:data,APP_ORIGIN:base,DEPLOY_MODE:'lan',DATABASE_URL:'',PGHOST:'',NODE_ENV:'test'}}).toString();
    const adminLink=operatorOutput.match(/http:\/\/127\.0\.0\.1:\d+\/#reset=[^\s]+/)?.[0];
    assert.ok(adminLink);
    assert.equal((await api('/api/reset-password','POST',{token:new URL(adminLink).hash.slice('#reset='.length),newPassword:'owner-new-password'})).status,200);
    assert.equal((await api('/api/me','GET',null,admin.cookie)).status,401);
    assert.equal((await api('/api/login','POST',{username:'owner',password:'owner-new-password'})).status,200);
  }finally{child.kill();await new Promise(resolveExit=>child.once('exit',resolveExit));await rm(data,{recursive:true,force:true});}
});
